name: hotel_app
description: Otel listeleme, karşılaştırma ve favori ekleme uygulaması (Firebase/Supa olmadan, local).
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^1.7.1
  # UI & yardımcı paketler
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  flutter_svg: ^1.1.6
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   
